name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: myawsbucket
        AWS_ACCESS_KEY_ID: 
        AWS_SECRET_ACCESS_KEY:  
        AWS_REGION: 'ap-south-1'   # optional: defaults to us-east-1
       
